### ISSUE TITLE
feature request: make this also work with brave search and searx instances

### ISSUE THREAD

**Issue by zombiehoffa** [wong2/chat-gpt-google-extension#1]
Hi, this is super cool. Could you do those of use who don't use google search a favor and add support for brave search *https://search.brave.com/) and searx instances (there are many, here, is an example of a popular one: https://searx.be/search)

**Comment by MikhailTNY** [comment]
Same for bing. Let me know if a separate issue should be filed for each search engine.

**Comment by maciej-trebacz** [comment]
> Hi, this is super cool. Could you do those of use who don't use google search a favor and add support for brave search *https://search.brave.com/) and searx instances (there are many, here, is an example of a popular one: https://searx.be/search)

Just ask ChatGPT to code that for you 😄

**Comment by Polydynamical** [comment]
Also DuckDuckGo !

**Comment by lolsu-de** [comment]
While we're at it, I would love to see this add Ecosia support as well. While it's not that popular globally, Europeans and especially Germans really like it.

**Comment by Polydynamical** [comment]
Alright, Brave, Searx, and Ecosia! I'll likely work on this tomorrow

**Comment by patrickcurl** [comment]
Another vote for Brave search far superior to google imho, and duckduckgo.

**Comment by Polydynamical** [comment]
@patrickcurl See PR #31

**Comment by ylluminate** [comment]
`https://searx.tiekoetter.com/` is the best Searx search instance as far as UI/UX goes. That's the one to add beyond the `.be` one noted.
