### ISSUE TITLE
Some search engines were removed again

### ISSUE THREAD

**Issue by MinmoTech** [wong2/chat-gpt-google-extension#101]
In this commit: https://github.com/wong2/chat-gpt-google-extension/commit/883219f3b40dcd58ebb995c0ed475a2307ef6c12 a few search engines were removed again, in particular I care about the searx.be removal.

Was there a reason for this and could this be restored?

**Comment by wong2** [comment]
Hi, I want to keep the supported search engine list as small as possible, and I've never heard of `searx.be` so I removed it. Is it a search engine used by many people?

**Comment by wong2** [comment]
Please request search engine here: https://github.com/wong2/chat-gpt-google-extension/issues/109
