### ISSUE TITLE
How to use in China, if there are any method to bypass openAI's area detection?

### ISSUE THREAD

**Issue by huangyebiaoke** [wong2/chat-gpt-google-extension#104]
![image](https://user-images.githubusercontent.com/26546591/207010829-222ed1c5-563c-4e85-868e-42a9ac799190.png)
Mirror website: https://gpt.chatapi.art (don't need login)
Try invoke http method:
API: https://gpt.chatapi.art/backend-api/conversation
Response: 
``` json
{
"detail": "Temporarily unavailable due to OpenAI limitations.（由于 OpenAI 的限制，暂时无法提供服务）"
}
```
Some one can help, please😥

**Comment by freekingxx** [comment]
sms 可以购买号码
