### ISSUE TITLE
In Google search engine it will show "Please login at chat.openai.com first" message

### ISSUE THREAD

**Issue by xiaoxiang-7** [wong2/chat-gpt-google-extension#105]
![顯示問題](https://user-images.githubusercontent.com/78013847/207019049-4829f00e-6736-4e97-bf46-93a414010d89.png)

I have already logged in at chat.openai.com, but the message "Please login at chat.openai.com first" is still displayed in the Google search engine.

How to solve it?

**Comment by xiaoxiang-7** [comment]
After a while, it was fine again, which is strange.

Sorry to bother you.
![又好了](https://user-images.githubusercontent.com/78013847/207028483-203489c3-8d84-420a-8896-252774c0c5bf.png)

**Comment by josStorer** [comment]
OpenAI added Cloudflare protections and Cloudflare tokens expire after 2 hours
