### ISSUE TITLE
I have login openai, when search with google, remind me login openai first, use ChatGPT for Google

### ISSUE THREAD

**Issue by RussellGee** [wong2/chat-gpt-google-extension#108]

**Comment by yinxx** [comment]
But it still doesn't work in China？

**Comment by wong2** [comment]
Make sure you can chat at https://chat.openai.com

**Comment by shiv19** [comment]
@wong2, yes I'm able to chat at https://chat.openai.com/
But it still asks me to login first
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/9407019/207429928-c5d4a92c-e633-4090-9305-f2ebe20a190e.png">

**Comment by shiv19** [comment]
@wong2 Clicking the link just takes me to my logged in ChatGPT instance (basically to the chat page). I have already passed through the Cloudflare security check :)
I can see that other users are also posting this issue on this repo.
I'll wait and watch.

**Comment by wong2** [comment]
@shiv19 Here is a new issue for discuss this problem: https://github.com/wong2/chat-gpt-google-extension/issues/112
