### ISSUE TITLE
when set extension site access to specific sites in chrome, we need add chat.openai.com in the list or it will encount cors error.

### ISSUE THREAD

**Issue by cjl3080434008** [wong2/chat-gpt-google-extension#11]
Is it a bug?

**Comment by wong2** [comment]
Is this an error message you encountered?

**Comment by cjl3080434008** [comment]
Access to fetch at 'https://chat.openai.com/api/auth/session' from origin 'chrome-extension://admendnbolgfafdbjdgdahlelnflpgia' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
background.js:440 Error: UNAUTHORIZED
    at getAccessToken (background.js:391:13)
    at async getAnswer (background.js:397:25)
    at async background.js:436:9

**Comment by wong2** [comment]
Have you logged in and been able to use https://chat.openai.com the web page to chat
?

**Comment by cjl3080434008** [comment]
Yes and when I add the https://chat.openai.com/* to the specific sites it works.

**Comment by wong2** [comment]
Which field have you added it into? `host_permissions`?

**Comment by cjl3080434008** [comment]
I changed `Extensions Detail > Site access > Allow this extension to read and change all your data on websites you visit` from `On all sites` to `On specific sites`.

**Comment by shacharhelmer** [comment]
I was not able to make it work for specific sites (tried `google.com`) even after allowing ` chat.openai.com` also.
(Using brave browser).

**Comment by cjl3080434008** [comment]
> I was not able to make it work for specific sites (tried `google.com`) even after allowing ` chat.openai.com` also. I also could not make it work setting `on click`. The extensions image background becomes white, and clicking it says: _reload page to use this extension_, even after reloading many times. (tested both in chrome and brave).

I think you need specific the site like this `https://chat.openai.com/*`
