### ISSUE TITLE
Expand yandex TLD permission

### ISSUE THREAD

**Issue by octaviusz** [wong2/chat-gpt-google-extension#111]
Hi, please add permission:
yandex.ru
yandex.by
yandex.kz
yandex.uz
yandex.com.tr

**Comment by KemGus** [comment]
Yeah, otherwise it doesn't work :/

**Comment by wong2** [comment]
PR welcome!

**Comment by vanditshah44** [comment]
Does it needs to be added in manifest? @wong2

**Comment by wong2** [comment]
Yes, just add them to the two manifest files should do it.

**Comment by vanditshah44** [comment]
Ok, so as I can see no one is assigned there so can you assign me?

**Comment by vanditshah44** [comment]
Created an Pull request after updating both manifest files with the urls
