### ISSUE TITLE
Please login at chat.openai.com first

### ISSUE THREAD

**Issue by vanditshah44** [wong2/chat-gpt-google-extension#112]
It worked for first 2-3 days, but after that when I google search anything it shows this prompt in place of results from the extension, I also tried logging into the account but after successfully logging in the results are same I am also attaching a screenshot 
![image](https://user-images.githubusercontent.com/80357669/207489760-6ee24efd-e14a-4304-b3df-9cffa6f73cd6.png)

**Comment by wong2** [comment]
OpenAI have added Cloudflare in front, you need to click the link for a Cloudflare security check, then everything works fine (for some unknown time)

**Comment by wong2** [comment]
Discussions about bypass Cloudflare: https://github.com/acheong08/ChatGPT/issues/261

**Comment by vrindavan** [comment]
So, at the moment there is no way get around the cloudflare thing?

**Comment by wong2** [comment]
No easy way, I'm still trying

**Comment by vrindavan** [comment]
Wait, this is fixed?

**Comment by wong2** [comment]
@vrindavan There are two problems: 
1. Brave browser shows this prompt event after login
2. The extension works, but users see this prompt once in a while

This issue describes the first one, which is severe but solved by change Brave settings

**Comment by vrindavan** [comment]
Hey so I just checked and it works without changing anything in Brave  (for me at least) but I use Cloudflare Warp (screenshot). I just checked and it works only when I disconnect to warp for some reason.

![image](https://user-images.githubusercontent.com/50140643/209161044-63026ab3-581d-460b-8502-340c3e960868.png)

**Comment by wong2** [comment]
OK, Cloudflare & Brave security behavior are black boxes, can't really understand

**Comment by vrindavan** [comment]
This fixed it for me in Brave without turning off Cloudflare: https://github.com/wong2/chat-gpt-google-extension#how-to-make-it-work-in-brave

**Comment by wong2** [comment]
Great

**Comment by sorfudu** [comment]
What is matter?
