### ISSUE TITLE
add button for use.

### ISSUE THREAD

**Issue by nacholaciar** [wong2/chat-gpt-google-extension#118]
We do a lot of searching on Google, which means that all the searches done are also done on chatGPT, which causes the system to crash. There will be occasions when we will not need chatGTP, therefore, we avoid consultation and unwanted use.
Adding a button that says: consult chatGTP? It would fix the problem.

**Comment by AngelofVerdant** [comment]
> We do a lot of searching on Google, which means that all the searches done are also done on chatGPT, which causes the system to crash. There will be occasions when we will not need chatGTP, therefore, we avoid consultation and unwanted use. Adding a button that says: consult chatGTP? It would fix the problem.

----------------------------------------------------------------------------------------------------------------------------------------------------

The Extension already gives you three different trigger modes 

:x: Always 
:x: When Query ends with Question Mark
:x: And Manually enabling 

That way when you don't wanna use it you can switch to  manual and trigger it only when you need to use it
