### ISSUE TITLE
XSS Vulnerability 

### ISSUE THREAD

**Issue by timemachine3030** [wong2/chat-gpt-google-extension#12]
https://github.com/wong2/chat-gpt-google-extension/blob/a966d230f7b772f6d144cf2db87ddc115ee43a8c/src/content-script/index.mjs#L19

you may want to change “innerHTML” to “textContent” before someone asks it how cross-site-scripting works. 

See also: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page

**Comment by wong2** [comment]
Thanks! Solved in https://github.com/wong2/chat-gpt-google-extension/commit/617eb2641e3f7edabbd89c5ce3dc36c8b1eb1468
