### ISSUE TITLE
Please pass Cloudflare security check at chat.openai.com

### ISSUE THREAD

**Issue by iztokinvest** [wong2/chat-gpt-google-extension#120]
![image](https://user-images.githubusercontent.com/90605919/208121692-477ecf30-fd20-41d7-a50f-962096ddbf67.png)
I get this message

**Comment by zhengbangbo** [comment]
This is because it really needs to be done.

**Comment by wong2** [comment]
You need to do this now. i'm still figuring out how to automatic it

**Comment by Cyber-Cowboy** [comment]
I also see this image constantly, despite passing Cloudflare security check

**Comment by wong2** [comment]
@Cyber-Cowboy OpenAI requires you to pass the cloudflare check every two hours, i think that's the reason

**Comment by Cyber-Cowboy** [comment]
@wong2 But I clicked the link and got to chat gpt as usual without captcha, after this I refreshed the search page and still got this message. Also I figured out that when I use Chrome instead of Brave everything works fine for some reason...

**Comment by wong2** [comment]
@Cyber-Cowboy that's very weird...

**Comment by Goldsucher07** [comment]
exactly same issue here

**Comment by wong2** [comment]
@Goldsucher07 are you still getting this warning after clicking the link and go back, refresh the search page?

**Comment by Puri12** [comment]
> @wong2 But I clicked the link and got to chat gpt as usual without captcha, after this I refreshed the search page and still got this message. Also I figured out that when I use Chrome instead of Brave everything works fine for some reason...

I also had this problem in the Brave browser.

**Comment by wong2** [comment]
I'll test on Brave

**Comment by wong2** [comment]
@Cyber-Cowboy @Puri12 Have you logged in at https://chat.google.com?

**Comment by Puri12** [comment]
> @Cyber-Cowboy @Puri12 Have you logged in at [chat.google.com](https://chat.google.com)?

Um, are you talking about chat.openai.com?
Yes, I have already logged in to https://chat.openai.com using my Google account.
I tried logging out and then logging back in, but the same message appears.

**Comment by Goldsucher07** [comment]
> @Goldsucher07 are you still getting this warning after clicking the link and go back, refresh the search page?




I should have done everything right?




https://user-images.githubusercontent.com/60298474/208243440-003b267f-0e8b-4c60-9dff-6d6c75f3c9c1.mp4

**Comment by wong2** [comment]
@Puri12 @Goldsucher07 You're doing things right, I'll debug this

**Comment by Puri12** [comment]
> @Puri12 @Goldsucher07 You're doing things right, I'll debug this, seems like some bug with Brave browser

![image](https://user-images.githubusercontent.com/5901912/208244008-b07f56e4-f5a9-422a-9b35-50d8048af697.png)
`Auto-redirect tracking URLs`
I tried several methods and turned off the above setting in the settings and it worked normally. :smiley:

**Comment by wong2** [comment]
@Puri12 Glad to hear that! @Goldsucher07 can you confirm that?

**Comment by wong2** [comment]
I think I understand the problem now, Brave browser have some security features enabled for a request, but these wasn't applied to requests from extension, so Cloudflare returns 403

**Comment by Goldsucher07** [comment]
> @Puri12 Glad to hear that! @Goldsucher07 can you confirm that?

kinda i now get this "Waiting for ChatGPT response..."

and after that an blank Box ? (see Image)

![image](https://user-images.githubusercontent.com/60298474/208246826-8d542077-b52e-4da4-bc12-e411da14a1b6.png)

**Comment by HOOLY123M** [comment]
the same broblem not fixed

**Comment by neoOpus** [comment]
This could help [Flaresolver](https://github.com/FlareSolverr/FlareSolverr)

**Comment by wong2** [comment]
@HOOLY123M what browser are you using?

**Comment by rgomezp** [comment]
Happens in Brave browser

**Comment by wong2** [comment]
@rgomezp Can you try https://github.com/wong2/chat-gpt-google-extension/issues/120#issuecomment-1356264089

**Comment by kkviks** [comment]
Disabling this option in `brave://settings/shields` solved this issue for me!
<img width="672" alt="image" src="https://user-images.githubusercontent.com/56562130/208826560-be43a435-6368-48f7-a526-cf5410da86cd.png">

**Comment by wong2** [comment]
@kkviks Thanks, I can confirm that is the cause.

**Comment by kmooventhan98** [comment]
@kkviks thanks **it's working now**

**Comment by Akshay-66** [comment]
@Marc-MMA 
It works pretty well in incognito mode or private tab,
You don't have to worry about the history, because chatGPT got that feature now, just login... If you are not satisfied with this, then try going for brave and do the following steps said by @Puri12

**Comment by qq280948982** [comment]
I have same issue on Chrome ...

**Comment by ameenfathullah** [comment]
I faced this issue on chrome and brave browser if i login chatgpt using Google Sign-in button @ "Continue with google"  

My problem solved when I try to sign in chatGPT using email address and password method instead of Google Sign-in Button. 

hope this guide can assist you to successfully display chatgpt result on google search page too.
