### ISSUE TITLE
Add theme config

### ISSUE THREAD

**Issue by wong2** [wong2/chat-gpt-google-extension#122]
Let user config:
* auto
* light
* dark

**Comment by ChiamakaUI** [comment]
Hi @wong2, I would love to work on this issue. Can it be assigned to me ?

**Comment by wong2** [comment]
sure go ahead

**Comment by wong2** [comment]
@ChiamakaUI Are you working on this? If not, I'm going to implement it.

**Comment by ChiamakaUI** [comment]
Hello @wong2, I am working on it
