### ISSUE TITLE
After the user clicked the thumbs-up/down icon, enable that he can redoo or undoo the action

### ISSUE THREAD

**Issue by IvanVnucec** [wong2/chat-gpt-google-extension#127]
When a user had already voted by clicking on thumbs up/down icon, enable it so he can undoo the action by clicking on the same icon, or he can cast different vote by clicking on the other icon.

![image](https://user-images.githubusercontent.com/50591550/208612402-e690bdb9-ea49-42f2-bb24-48fffaf464f6.png)

**Comment by wong2** [comment]
This is by design, ChatGPT feedback API doesn't allow changing your vote
