### ISSUE TITLE
Request support for Opera

### ISSUE THREAD

**Issue by Vennicks** [wong2/chat-gpt-google-extension#129]
I ran through a problem, I'm currently using Opera GX and I tried to add the extension, but nothing display.
![image](https://user-images.githubusercontent.com/60688703/208645168-9ec42748-225c-4694-a582-ef6f1a872066.png)
![image](https://user-images.githubusercontent.com/60688703/208645228-19722151-54f0-447a-91bc-71b972ac8faf.png)

**Comment by Vennicks** [comment]
You have to give access to search result in the extensions menu to make it work, so maybe you could add it to the authorization.
I made it works.

**Comment by wong2** [comment]
What do you mean by "give access to search result in the extensions menu", can you show me a screenshot?

**Comment by Vennicks** [comment]
Right click on the extension menu -> Manage extension -> scroll down to this option and enable it:
![image](https://user-images.githubusercontent.com/60688703/208646850-d2a4614a-1a90-4fe7-a61f-8eedeb9c5c24.png)
It's disable by defaults

**Comment by wong2** [comment]
OK, that's an Opera specific setting, which can not be set by the extension itself. I'll add a notice in README. Thanks for bring this up!
