### ISSUE TITLE
Make an option to delete the "search chat" from ChatGPT

### ISSUE THREAD

**Issue by Shamane2000** [wong2/chat-gpt-google-extension#130]
When you search something with google, then every search request results in a "new chat" entry in ChatGPT. 
Please make a option to don't do this, or delete it imeadeatly. (ONLY the one, who was created, not "all") 

Thanks a lot!

**Comment by wong2** [comment]
Thanks for bringing this up! I'll see how to solve it.

**Comment by wong2** [comment]
I'll add all "search chats" to one conversation, so they don't mess up with your history list.

**Comment by wong2** [comment]
I met some problem when trying to reuse one conversation, so I implemented auto delete the search conversation now.

**Comment by 0xdevalias** [comment]
Released in:

- https://github.com/wong2/chat-gpt-google-extension/releases/tag/v1.9.0

**Comment by wong2** [comment]
v1.9.0 published to Webstore

**Comment by bigplayer-ai** [comment]
It is not working for me, The option is grayed out. How can I Fix this issue?

**Comment by wong2** [comment]
Hi the option is readonly currently, which means this feature is always enabled

**Comment by bigplayer-ai** [comment]
> Hi the option is readonly currently, which means this feature is always enabled

It is always enabled, But It is not working properly. I keep having opened conversation (from google searches) and the extension never deletes them.

**Comment by wong2** [comment]
Do you mean every conversation? That's weird, I've always want to reproduce that
