### ISSUE TITLE
Does not work on cn-bing

### ISSUE THREAD

**Issue by 2catycm** [wong2/chat-gpt-google-extension#133]
https://cn.bing.com/
 is bing search engine. It looks like this:
![image](https://user-images.githubusercontent.com/41530341/209083183-8e184c5b-d33a-4d56-9fc6-f73d812fb58b.png)

And it is currently not supported. 

the extension works well on google and baidu.

**Comment by wong2** [comment]
I'll add cn.bing.com to the list: https://github.com/wong2/chat-gpt-google-extension/blob/main/src/manifest.json#L214

**Comment by wong2** [comment]
Fixed in https://github.com/wong2/chat-gpt-google-extension/commit/dd654ea5a0df56a9e74dc431805f698915a37272

**Comment by 2catycm** [comment]
👍awesome



---Original---
From: "Wang ***@***.***&gt;
Date: Thu, Dec 22, 2022 22:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wong2/chat-gpt-google-extension] Does not work on cn-bing (Issue#133)




 
Fixed in dd654ea

**Comment by 2catycm** [comment]
I compiled it and it works well on my browser now.

**Comment by wong2** [comment]
Great
