### ISSUE TITLE
Asking me to pass the cloudflare security check, but even that doesn't work

### ISSUE THREAD

**Issue by 0xCUB3** [wong2/chat-gpt-google-extension#134]
![image](https://user-images.githubusercontent.com/94565160/209138866-a87bf224-0668-4225-834d-be6cb392e8d2.png)

**Comment by wong2** [comment]
What browser are you using?

**Comment by 0xCUB3** [comment]
brave

**Comment by wong2** [comment]
Please follow https://github.com/wong2/chat-gpt-google-extension#troubleshooting
