### ISSUE TITLE
conversation cleanup

### ISSUE THREAD

**Issue by LaysDragon** [wong2/chat-gpt-google-extension#135]
Now ChatGPT have the new chat list feature,but the extension basicly spam the list with every single conversation from search and made the chat list unuseuable.😂 
I think it would be better to if extension have the feature to auto cleanup the conversation generated by the extension.
![image](https://user-images.githubusercontent.com/10185394/209194020-a6e9adbb-32e3-4f9f-aa81-4729e931d833.png)

**Comment by wong2** [comment]
Hi, please make sure you have upgraded to v1.9.0, this version added exactly what you requested.
