### ISSUE TITLE
Add margins between ChatGPT results paragraphs

### ISSUE THREAD

**Issue by IvanVnucec** [wong2/chat-gpt-google-extension#137]
On multi-paragraph text it is hard to distinguish how the text is divided between paragraphs. It would be easier to read if there is margins between them. Below are examples with no margins and with 10px (bottom only) paragraph margins:
![image](https://user-images.githubusercontent.com/50591550/209343525-a3679704-f23b-4b25-b313-897279456541.png)
![image](https://user-images.githubusercontent.com/50591550/209343541-d4286a70-1ae8-40e2-a1e4-42e6b3978ea7.png)

**Comment by wong2** [comment]
Resolved https://github.com/wong2/chat-gpt-google-extension/commit/7c44022f834f4ff0e68203414d0731f02a8afa28
