### ISSUE TITLE
ChatGPT output animation speed up

### ISSUE THREAD

**Issue by JiapengLi** [wong2/chat-gpt-google-extension#138]
**Describe the bug**
ChatGPT atimation is slow (pretend it is human-like),
is it possible to fine tune through this plugin?

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by josStorer** [comment]
duplicate of #136

> wong2: That's out of our control, the API is running by OpenAI

**Comment by wong2** [comment]
Do you mean ChatGPT slow down the animation on purpose? Even if that's true, this extension did not do that.
