### ISSUE TITLE
White links on search

### ISSUE THREAD

**Issue by pernydev** [wong2/chat-gpt-google-extension#144]
**Describe the bug**
For some reason ChatGPT for Google makes all the unclicked links white, rather than blue. This behaviour is new and did not happen a few weeks ago.

With extension:
![image](https://user-images.githubusercontent.com/83672513/209482954-2b903528-6b25-48a8-a3fa-8cb88cc7d9bb.png)

Without:
![image](https://user-images.githubusercontent.com/83672513/209482988-3be4345d-74b7-4e1e-bd90-b956e069d785.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21
 - Browser: Firefox

**Comment by wong2** [comment]
Fixed in v1.10.1
