### ISSUE TITLE
Reduced Google Search Bar Icons

### ISSUE THREAD

**Issue by gitpro2005** [wong2/chat-gpt-google-extension#145]
**Describe the bug**
Google search bar icons (keyboard icon, microphone icon, and Lens) are being resized when activating the extension, becoming noticeably smaller. (see screenshot below)

![image](https://user-images.githubusercontent.com/80659357/209487755-6ab84ea6-8649-4796-826d-e3d010a65f90.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge

**Comment by wong2** [comment]
Fixed in v1.10.1
