### ISSUE TITLE
ChatGPT for Google makes Google Search links grey.

### ISSUE THREAD

**Issue by Pico109** [wong2/chat-gpt-google-extension#147]
### ChatGPT for Google makes Google Search links grey.

Windows 11 22H2 
Firefox 108.0.1

ChatGPT for Google disabled
![image](https://user-images.githubusercontent.com/81302994/209587697-281c19c5-e218-4fd2-938d-9a2319de3162.png)

ChatGPT for Google enabled
![image](https://user-images.githubusercontent.com/81302994/209587663-d135804a-bb94-4a4f-961f-b06fc3fc5989.png)

**Comment by wong2** [comment]
Please upgrade to latest version. This was fixed
