### ISSUE TITLE
Why frequent disconnection？

### ISSUE THREAD

**Issue by geekyouth** [wong2/chat-gpt-google-extension#149]
**Describe the bug**
Why frequent disconnection? It is necessary to manually jump to the official website repeatedly, and then refresh it to return to normal.
Today is 12-28 and the problem still exists.
How can I improve? ? ? thanks

**Desktop (please complete the following information):**
 - OS: win10

 - Browser 
 关于 Cent Browser
Cent Browser 徽标
Cent Browser
版本 5.0.1002.276（正式版本） （64 位） (Chromium 102.0.5005.167)

![image](https://user-images.githubusercontent.com/12899262/209775956-bd20da9f-be72-461a-af36-24f5706f8ded.png)

**Comment by wong2** [comment]
This is a restriction by OpenAI, which requires passing a security check every two hours
