### ISSUE TITLE
Please login and pass Cloudflare check at chat.openai.com

### ISSUE THREAD

**Issue by Baiyssy** [wong2/chat-gpt-google-extension#150]
**Describe the bug**
always show
Please login and pass Cloudflare check at chat.openai.com
Even if I have already logged in to this website.

**Desktop (please complete the following information):**
 - Windows 10]
 - Chrome 110.0.5478.4 x64

**Comment by Temanor** [comment]
I am having the same issue with firefox

**Comment by wong2** [comment]
Can you post a video?

**Comment by crunde85** [comment]
same issue for me using Brave

**Comment by crunde85** [comment]
> 


https://user-images.githubusercontent.com/41240002/210122751-74039655-2aae-4f7d-a7ed-94de6308342c.mp4

**Comment by crunde85** [comment]
> Can you post a video?

I attached one to my last comment.

**Comment by wong2** [comment]
@crunde85 You're using Brave, have you followed this? https://github.com/wong2/chat-gpt-google-extension#troubleshooting

**Comment by BrianLiu2005** [comment]
The same error occurs in Google Chrome as well

**Comment by wong2** [comment]
@BrianLiu2005 can you post a video?

**Comment by wong2** [comment]
Please note

There is a restriction by OpenAI, which requires passing a security check every two hours

**Comment by BrianLiu2005** [comment]
Ah, I believe that's the error I'm referring to

**Comment by BrianLiu2005** [comment]
![Screenshot (316)](https://user-images.githubusercontent.com/59778508/210126267-b89b2492-9ae0-43b7-bc2e-f341389d9107.png)
For reference

**Comment by BrianLiu2005** [comment]
Do you have any suggestions for workarounds? Otherwise, it would be a very irritating aspect of a really neat extension

**Comment by wong2** [comment]
No solution yet.

**Comment by crunde85** [comment]
> @crunde85 You're using Brave, have you followed this? https://github.com/wong2/chat-gpt-google-extension#troubleshooting

This worked for me, thanks!

**Comment by mumuyanyan** [comment]
I am having the same issue
Please login and pass Cloudflare check at [chat.openai.com](https://chat.openai.com/)
OpenAI requires passing a security check every once in a while.
