### ISSUE TITLE
Failed to load response from ChatGPT: [object Object]

### ISSUE THREAD

**Issue by vrindavan** [wong2/chat-gpt-google-extension#151]
**Describe the bug**
It's returning the String representation instead of the actual result.
![image](https://user-images.githubusercontent.com/50140643/209961125-e13184ea-ff70-46aa-8fe5-f50c456126d8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave (with fingerprint toggle off as mentioned in the FAQs]

**Comment by kaka77** [comment]
+1

**Comment by wong2** [comment]
Improved the error message: https://github.com/wong2/chat-gpt-google-extension/commit/65e81decbc4defea20e598041afa387d64c7d05b
