### ISSUE TITLE
I made an extension for Youchat AI based on your work

### ISSUE THREAD

**Issue by fedebotu** [wong2/chat-gpt-google-extension#154]
Hi there! 
First of all, great job with your extension. It has helped me many times when searching on Google - sometimes ChatGPT gives better answers than the classic search engine!

So, I made an [extension](https://github.com/fedebotu/youchat-google-extension) based on your work for [Youchat AI](https://you.com/search?q=what%20was%20the%20recent%20breakthrough%20in%20fusion%20research%3F) (note that I am not affiliated with them). This has some advantages over ChatGPT:
- Does not need login
- Knows about recent events (integrated with a search engine)
- Cites sources
- Faster response time

On the flip side, the quality of the answers is not as good as ChatGPT. It turns out one can use both extensions so you can have both chatbots answer at the same time, providing more variety in the answers:

![Screenshot](https://github.com/fedebotu/youchat-google-extension/blob/main/screenshots/youchat_chatgpt.png?raw=true)

I thought that perhaps your extension could include in the future other chatbots as well (that users could choose from), if not multiple at the same time!

**Comment by wong2** [comment]
Nice work! I think let user choose AI providers is a nice idea.

**Comment by GovindKrishnan** [comment]
Would really love to see an All-in-One AI Assistant like that
