### ISSUE TITLE
Can you add the ability to chat with ChatGPT on any website for the extension ?

### ISSUE THREAD

**Issue by xiaoxiang-7** [wong2/chat-gpt-google-extension#156]
Does this extension work as in the picture below?
It's inconvenient to only have your extension available on the search engine page.

![annotely_image-1](https://user-images.githubusercontent.com/78013847/210084217-0eb10cba-6c88-4740-9d65-d04b3fa4dc63.png)

**Comment by wong2** [comment]
Nope
