### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by Oli6464** [wong2/chat-gpt-google-extension#158]
Is it possible to change language for chatgpt extension answers?

**Comment by wong2** [comment]
Which language do you want?

**Comment by Wkb2317** [comment]
> Which language do you want?
Author, hello. Can you provide Chinese? thanks

**Comment by vin3108** [comment]
and please how to change to french

**Comment by JeremieAucher** [comment]
it should be possible to prefix the requests with something like: (answers in French)

**Comment by andy00614** [comment]
I think it can add a new option to config current language in options page, then every question can auto add a suffix, for example: I want to ask "what is javascript", if i config french as default, then question will auto change to "what is javascript(in french)". I have tested, it's support by chatGPT.
  If this solution is feasible, I‘m glad to be involved in implementing it @wong2

**Comment by wong2** [comment]
@andy00614 That's a nice solution, I like it.

**Comment by andy00614** [comment]
> 

I have pushed a pr, please review. Thanks wong

**Comment by wong2** [comment]
Implemented by @andy00614

**Comment by JeremieAucher** [comment]
That's exactly what I suggested, but thanks anyway :)

**Comment by wong2** [comment]
@JeremieAucher Yes, thanks!
