### ISSUE TITLE
Chat gpt interface gets cut out if youre looking for products on google.com

### ISSUE THREAD

**Issue by AbishekSoti** [wong2/chat-gpt-google-extension#163]
![image](https://user-images.githubusercontent.com/85747087/210495746-dae0881d-7158-4317-b0b5-294345925cd9.png)

**Comment by wong2** [comment]
got it.

**Comment by D4VIDBRAVO** [comment]
hola

**Comment by wong2** [comment]
Fixed: https://github.com/wong2/chat-gpt-google-extension/commit/ad6282381c23d31b6b73a5543119fa227c3bcd29
