### ISSUE TITLE
Failed to load response from ChatGPT

### ISSUE THREAD

**Issue by geekyouth** [wong2/chat-gpt-google-extension#165]
**Describe the bug**
```
Failed to load response from ChatGPT:
{"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}
```

**Desktop (please complete the following information):**
 - OS: [ Windows]
 - Browser [chrome]

**Comment by wong2** [comment]
Are you opening two tabs at the same time?

**Comment by mburakergenc** [comment]
Having the same issue after a network error.

**Comment by mauxion** [comment]
the same issue with my first question (only one tab available)
