### ISSUE TITLE
stuck on Waiting for ChatGPT response...

### ISSUE THREAD

**Issue by FormalSnake** [wong2/chat-gpt-google-extension#166]
**Describe the bug**
It is stuck regardless of the question.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Arc (Based on barebones chromium)

**Comment by wong2** [comment]
Sometimes it will stuck, should work after some refresh

**Comment by FormalSnake** [comment]
> Sometimes it will stuck, should work after some refresh

I have tried, and a refresh does not work.
What type of errors should I look for?
