### ISSUE TITLE
it doesn't work with Getpage search engine 

### ISSUE THREAD

**Issue by Anmolratn** [wong2/chat-gpt-google-extension#167]
**Describe the bug**
It doesn't work with Getpage search engine ([www.getpage.rf.gd](https://www.getpage.rf.gd) ) 

Please enable this extension for Getpage. 

Browser : Chrome, Windows 7

**Comment by wong2** [comment]
Request search engines here: https://github.com/wong2/chat-gpt-google-extension/issues/109
