### ISSUE TITLE
Issue with layout

### ISSUE THREAD

**Issue by ldblake** [wong2/chat-gpt-google-extension#170]
Google search results are overlapping ChatGPT result. ChatGPT result needs to be horizontally further over on the page

**Comment by wong2** [comment]
Can you add a screenshot?

**Comment by ldblake** [comment]
I could but I remembered I have an extension installed: Search Results
Preview <https://bit.ly/3CtZeEo>  This could be the cause as it changes the
default page layout. So it may not be an issue for other users. Thanks for
your attention.

--
Leland Blake
***@***.***

**Comment by Baysel8** [comment]
![image](https://user-images.githubusercontent.com/122181512/211171039-55dd8816-0614-4708-b65c-b9e0d157d072.png)
It happend to me aswell (so far only with this shopping thing)

**Comment by wong2** [comment]
@Baysel8 this case has been fixed. will be released in next version
