### ISSUE TITLE
disconnected too often

### ISSUE THREAD

**Issue by X-x2** [wong2/chat-gpt-google-extension#171]
It is very troublesome to log in again on the ChatGPT website every few minutes

**Comment by geekyouth** [comment]
me too

**Comment by wong2** [comment]
Is it that frequent? I believe the session will last hours

**Comment by X-x2** [comment]
> Is it that frequent? I believe the session will last hours

watch this. I ask one question, and after 3 minutes, I ask another question on the same page, and it requires me log in again.
![未命名图片](https://user-images.githubusercontent.com/82787363/211199900-86631ca5-58b9-4525-ab58-ce824afdc0bb.png)

**Comment by wong2** [comment]
That's weird. I'll keep looking

**Comment by X-x2** [comment]
> That's weird. I'll keep looking

Many thanks！I have been troubled by this problem since the beginning. To add， I ues vpn to access google.
