### ISSUE TITLE
Can I use the token that others have logged in

### ISSUE THREAD

**Issue by ferrymo** [wong2/chat-gpt-google-extension#173]
I modified the session_token, but 403

I modified the following files
src/background/index.ts

The following functions have been overridden

`
const FIXED_KEY_ACCESS_TOKEN="xxxxxxxxxx"
// async function getAccessToken(): Promise<string> {
//   if (cache.get(KEY_ACCESS_TOKEN)) {
//     return cache.get(KEY_ACCESS_TOKEN)
//   }
//   const resp = await fetch('https://chat.openai.com/api/auth/session')
//   if (resp.status === 403) {
//     throw new Error('CLOUDFLARE')
//   }
//   const data = await resp.json().catch(() => ({}))
//   if (!data.accessToken) {
//     throw new Error('UNAUTHORIZED')
//   }
//   cache.set(KEY_ACCESS_TOKEN, data.accessToken)
//   return data.accessToken
// }

async function getAccessToken(): Promise<string> {

  if (cache.get(KEY_ACCESS_TOKEN)) {
    return cache.get(KEY_ACCESS_TOKEN)
  }

  cache.set(KEY_ACCESS_TOKEN, FIXED_KEY_ACCESS_TOKEN)
  return FIXED_KEY_ACCESS_TOKEN
}
`

**Comment by wong2** [comment]
403 is returned by cloudflare security check.

**Comment by ferrymo** [comment]
> 

Can you help me solve this problem

**Comment by wong2** [comment]
You need to manually visit chat.openai.com, pass the security check, then Cloudflare will set a cookie. Then you're fine.

**Comment by ferrymo** [comment]
> You need to manually visit chat.openai.com, pass the security check, then Cloudflare will set a cookie. Then you're fine.

需要将登录的cookie复制到未登录的浏览器，对吗

**Comment by ferrymo** [comment]
> You need to manually visit chat.openai.com, pass the security check, then Cloudflare will set a cookie. Then you're fine.

need to copy the logged in cookie to the browser that is not logged in, right

**Comment by wong2** [comment]
不太确定复制cookie到另一个浏览器是否可行，有可能导致Cloudflare判断为需要再次进行检查

**Comment by ferrymo** [comment]
> 不太确定复制cookie到另一个浏览器是否可行，有可能导致Cloudflare判断为需要再次进行检查

行吧，我昨天晚上写死session_token还成功了，今天上午就不行了，
