### ISSUE TITLE
chatgpt answer cuts off and doesnt continue 

### ISSUE THREAD

**Issue by MaCrO093** [wong2/chat-gpt-google-extension#175]
**Browser: opera gx 
Os: Windows 10 home**

Whenever the prompt is something thats (i think) over 20-30 lines down it cuts off, it always cuts off when its about to go to the next line
![image](https://user-images.githubusercontent.com/107784730/211463563-85ec522f-5f6c-4f0e-a756-7bf9d931d17d.png)
![image](https://user-images.githubusercontent.com/107784730/211464210-2ebcc011-7f90-420a-bbee-d27a022bb33b.png)
ive tried in incognito with the only other extension being adblockplus
The only other chatgpt extensions i have is merlin and webchatgpt, ive also tried turning off "search on the web" and repeating the result for the same thing to happen
![image](https://user-images.githubusercontent.com/107784730/211463988-0006293b-4a1e-443b-960a-2498dfa0f4f0.png)
![image](https://user-images.githubusercontent.com/107784730/211464262-a3433129-f7be-4c62-ab94-dc8a50776dcb.png)

**Comment by MaCrO093** [comment]
by the way this isnt a part of the issue, but if its not too much work can you add the search on the web button if you have webchatgpt or a seperate feature that toggles search on the web in the settings or above/below the answer?? it might be cool if chatgpt doesnt know/gives a bad answer or something. i know i can just visit the website and toggle it with webchatgpt but its more efficient this way i guess

**Comment by rgomezp** [comment]
I am seeing the same exact issue.

**Comment by wong2** [comment]
Fixed in latest version, still waiting for Chrome Web store review.

**Comment by wong2** [comment]
1.14.3 published.
