### ISSUE TITLE
Failed to load response from ChatGPT: {"detail":{"message":"Unauthorized - Access token is missing"}}

### ISSUE THREAD

**Issue by skypoc** [wong2/chat-gpt-google-extension#179]
I have logged into chatGPT on Chrome, but it shows the following error.

Failed to load response from ChatGPT:
{"detail":{"message":"Unauthorized - Access token is missing"}}

**Comment by aini332456** [comment]
i faced the problem and resolved, i guess the reason is my country was baned by openai, the problem was resolved when i changed the accept-language header
