### ISSUE TITLE
ChatGPT answers getting cut off

### ISSUE THREAD

**Issue by alex21** [wong2/chat-gpt-google-extension#180]
I can't see complete answer. The responce text is cutted and I can't see all responce..
This happen multiple times.
![Screenshot 2023-01-11 09_33_56-Window](https://user-images.githubusercontent.com/13554635/211758012-3151160c-3c19-4d9a-bd92-a53ae11cf57f.png)
You can see on picture. It's serbian language but same happen on english too

**Comment by wong2** [comment]
Fixed in latest version, still waiting for Chrome Web store review.

**Comment by alex21** [comment]
What about firefox? 
I'm using firefox and I didn't get notification about update

**Comment by wong2** [comment]
@alex21 Firefox version has been updated just now, the version is 1.14.3 https://addons.mozilla.org/en-US/firefox/addon/chatgpt-for-google/

**Comment by wong2** [comment]
Please let me know if the issue is fixed.

**Comment by alex21** [comment]
So far so good. 
Thank you very much!

**Comment by wong2** [comment]
Glad to hear that.
