### ISSUE TITLE
Doesn't work. Asks me to login

### ISSUE THREAD

**Issue by adefaria** [wong2/chat-gpt-google-extension#183]
**Describe the bug**
This doesn't work. Asks me to login. I login. Asks me to login. Rinse and repeat...

**Desktop (please complete the following information):**
Ubuntu 22.04
Brave Latest

**Comment by adefaria** [comment]
Fixed by https://github.com/wong2/chat-gpt-google-extension#how-to-make-it-work-in-brave

Sorry, I should have searched more...

**Comment by wong2** [comment]
No problem!
