### ISSUE TITLE
Thanks for the great extension. I created a youtube summarization with inspiration from your codebase. 

### ISSUE THREAD

**Issue by theaifan** [wong2/chat-gpt-google-extension#184]
Just wanted to say thanks for creating this extension, I use it all the time. 
I created this one as well inspired by your codebase.  Learned a lot from your clean code by the way. 
https://chrome.google.com/webstore/detail/youtube-videos-summarizat/agjkjablkiapmpbeglmdcmhnihlofija

**Comment by wong2** [comment]
Congrats on the launch
