### ISSUE TITLE
Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by Cheerstoast** [wong2/chat-gpt-google-extension#185]
An error often happens: Unexpected non-whitespace character after JSON at position 4
![Screen Shot 2023-01-12 at 6 19 54 pm](https://user-images.githubusercontent.com/107456948/212002506-efdf1a9d-2d0a-4859-8674-6021f0394381.png)

**Comment by theaifan** [comment]
I think this is a new response that chatgpt returns that is not json and not an error
@wong2  you might want to wrap this with a try catch to avoid future responses that are not json 
https://github.com/wong2/chat-gpt-google-extension/blob/main/src/background/index.ts#L73

**Comment by wong2** [comment]
@Cheerstoast @theaifan This has been fixed in v1.14.3  Please upgrade and check again
