### ISSUE TITLE
chatgpt extension disappear on google search after some time.

### ISSUE THREAD

**Issue by bigplayer-ai** [wong2/chat-gpt-google-extension#194]
**Describe the bug**
When searching on google, ChatGpt extension tend to answer, while it writes the answer it just disappears and does not show me the result by the end.
before its disappearance
![Clip_20230121_193129](https://user-images.githubusercontent.com/119108387/213879448-91e21091-c063-4811-8f82-fd14705e95f5.png)
after that chatgpt extension just disappears from the right pane.
**Desktop (please complete the following information):**
 - OS: Windows 11 22h2 build 22621
 - Browser chrome Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by wong2** [comment]
When it disappears, can you scroll to the bottom of the page, and see if the chatgpt answer is there? And if so, can you screenshot that?

**Comment by wong2** [comment]
OK, fixed. Will release in next version.

**Comment by wong2** [comment]
Released

**Comment by sunnyszy** [comment]
Hi, I have a similar problem again:

![image](https://user-images.githubusercontent.com/11472767/227069003-3bed3c6f-7280-458f-91fa-4009bdc17c71.png)

OS: Windows 10 Pro 20H2 19042.1706
Browser chrome Version 111.0.5563.110 (Official Build) (64-bit)
