### ISSUE TITLE
code highlight

### ISSUE THREAD

**Issue by yesmeck** [wong2/chat-gpt-google-extension#2]
It appears that  ChatGPT returns a markdown format. Using a markdown rendering library would make the results more readable.

**Comment by wong2** [comment]
That's definitely in the TODO

**Comment by jameszu** [comment]
Hi there, 
I managed to get the CSS code highlighted but not the other languages : (

<img src="https://user-images.githubusercontent.com/41566813/206663162-0c485611-9397-4c2c-a35c-213021194154.png" alt="CSS code highlight" height="500"/>


Here is the response from the API, as you can see it includes CSS  after ` ``` `

<img src="https://user-images.githubusercontent.com/41566813/206665848-5dbb446b-960b-4a4e-9c41-ae19d8c3c499.png" alt="CSS code response" width="500"/>


It turns out the chatgpt API only response ` ``` ` without the language identifier for language like js, python, java and etc. The following screenshot shows part of the response when asking "blinking effect in javascript"
<img src="https://user-images.githubusercontent.com/41566813/206666031-7242c242-fe98-41e3-a6ef-4c014512c7f0.png" alt="jscode response" width="500"/>


Shall I create a PR or shall we wait and see if anyone else has a better idea on code highlights?
Cheers : )

**Comment by wong2** [comment]
I'm curious about your current approach

**Comment by jameszu** [comment]
Added the highlightjs css file and used the code from markdown-it documentation as the following
https://markdown-it.github.io/markdown-it/
<img src="https://user-images.githubusercontent.com/41566813/206667914-8afd37b0-38a7-4e52-b4c8-a85778e85e07.png" alt="highlightjs code" width="500"/>

**Comment by jjroley** [comment]
You could try`hljs.highlightAuto()`
