### ISSUE TITLE
Suggestion Text to Speech

### ISSUE THREAD

**Issue by luisrguerra** [wong2/chat-gpt-google-extension#204]
A feature that would be very interesting would be to implement a button that reads the chatGPT text with voice using the "text to speech engine" that already comes in Chrome.

Example of how to implement it:
[https://codepen.io/SteveJRobertson/pen/emGWaR](https://codepen.io/SteveJRobertson/pen/emGWaR)

**Comment by wong2** [comment]
That's interesting, but I don't think many users would use it.

**Comment by aidantorrence** [comment]
@wong2 that's wrong, reading text with audio is extremely popular
