### ISSUE TITLE
Adds Bing Engine support

### ISSUE THREAD

**Issue by Peri-albert** [wong2/chat-gpt-google-extension#22]
Can you add Bing Engine support?

**Comment by vinceycodes** [comment]
Yes, I use Bing and this would be amazing! Do you think you can make this? @wong2

**Comment by GHYOWEE** [comment]
Can you add Baidu Engine support?

**Comment by josStorer** [comment]
> Can you add Bing Engine support?

> Can you add Baidu Engine support?

i've add here #31
