### ISSUE TITLE
为什么Google搜索里chatgpt给的答案不尽如人意？

### ISSUE THREAD

**Issue by zhl111** [wong2/chat-gpt-google-extension#25]
这里的答案是不正确的，而且错误较多。
![image](https://user-images.githubusercontent.com/29135984/205674168-bebc2d35-3d20-4cb0-9b74-29f40a84f982.png)
而它自己网站的答案非常靠谱，这是怎么造成的呢？是不同的知识库吗？咱们的插件是否可以调用？
![image](https://user-images.githubusercontent.com/29135984/205674759-5b964644-e6f8-4708-a04d-47076e193eda.png)

**Comment by wong2** [comment]
ChatGPT对同一个问题也可能产生多种回答
