### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by NewsGuyTor** [wong2/chat-gpt-google-extension#3]
This needs to be a Firefox extension, looks really useful.

**Comment by wong2** [comment]
I'll try to build a Firefox version!

**Comment by vinceycodes** [comment]
> I'll try to build a Firefox version!

Thank you so much!

**Comment by wong2** [comment]
Sadly, Firefox doesn't support manifest v3, which makes it harder for the support..

**Comment by tizee** [comment]
> Sadly, Firefox doesn't support manifest v3, which makes it harder for the support..

@wong2 Just downgrading to version 2 is okay since your code is compatible enough. See #18

**Comment by wong2** [comment]
Thanks to @tizee , Firefox has been supported
