### ISSUE TITLE
Adding RTL support for queries made in Hebrew/Arabic

### ISSUE THREAD

**Issue by ron-azbel** [wong2/chat-gpt-google-extension#32]

**Comment by wong2** [comment]
Can you be more specific?

**Comment by ron-azbel** [comment]
Hebrew and Arabic are written from right to left. The default CSS setting for text formatting is always left to right - which messes up the appearance and readability of sentences.

[Example](https://i.imgur.com/VYJVqVX.png)

In the example above you can see that the quotation marks appear on the left-most part of the sentence, although it should appear in the middle of the sentence (I added a text box of how the text should appear with `direction: rtl` added to the CSS).
