### ISSUE TITLE
Use text-davinci-003 instead of 002

### ISSUE THREAD

**Issue by greguintow** [wong2/chat-gpt-google-extension#33]
I saw in the code that it's using `text-davinci-002-render` instead of `text-danvinci-003` which is GPT 3.5 that gives more detailed responses, any reason for that?

https://github.com/wong2/chat-gpt-google-extension/blob/6ff61d2d62fb6e666338f9089603512f2a93fe8b/src/background/index.mjs#L44

Could you update to `text-davinci-003`?

**Comment by wong2** [comment]
I just copied that from requests on `chat.openai.com`, which means they're also using `text-davinci-002-render`
