### ISSUE TITLE
GPT showing up two answers with narrow width at the same time

### ISSUE THREAD

**Issue by weiweizh** [wong2/chat-gpt-google-extension#37]
It's showing up two answers simultaneously, which is great. But it reduces readability as the width of both answers is too narrow. 
If it's the intended behavior, it'd be great to add a way to navigate through two or even more answers.

Even better, it'd be great to add micro-interactive feedback to see how people rate/react to those answers.

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/6616226/205933827-44451c35-05c7-47b0-b857-efc1beb8d0da.png">

**Comment by wong2** [comment]
Hi, it seems you have installed two versions of this extension. Please check and uninstall one of them(maybe the local installed one)
