### ISSUE TITLE
Can I extend extension to additional AI powered bot.

### ISSUE THREAD

**Issue by iShelar** [wong2/chat-gpt-google-extension#46]
Hi @wong2 ,

Can I add one more AI-powered bot to this chrome extension? This is basically helpful for K 12 Students to learn Science, Maths topic & also this site has interactives to help students visualize & learn concepts quickly. 

If it has interactive then we will direct them to that specific resource.

**Comment by wong2** [comment]
Hi, I'd like to keep this extension focused on ChatGPT only. You can make a fork anyway.
