### ISSUE TITLE
Support Google Dark Theme/Mode (dark borders)

### ISSUE THREAD

**Issue by furyzenblade** [wong2/chat-gpt-google-extension#49]
-> https://github.com/wong2/chat-gpt-google-extension/blob/1f5076b0bffcb4f0cb21846bb520d6ac108a6ed8/src/styles.css#L4
The color is slightly darker when using the google dark theme (https://www.google.com/preferences#appearance)
its #3c4043 - rgb(60, 64, 67)
instead of #dadce0 - rgb(218, 220, 224)

**Comment by wong2** [comment]
got it

**Comment by wong2** [comment]
Fixed https://github.com/wong2/chat-gpt-google-extension/commit/c17d7b18f6e26291d277021305584ef6763d67c3

**Comment by ba32107** [comment]
I think dark mode support should be about more than just the borders. This is how the extension looks like for me:
![image](https://user-images.githubusercontent.com/26036493/206835891-b4c26389-9cd6-48a5-b921-3b84194805fc.png)

It feels quite out of place. Would it be possible to have dark background as well?

**Comment by wong2** [comment]
@ba32107 Can you try out v1.3.0? https://github.com/wong2/chat-gpt-google-extension/releases/tag/v1.3.0

**Comment by ba32107** [comment]
Yep, I just tried, bit different but still has a white background:

![image](https://user-images.githubusercontent.com/26036493/206838652-d58a4668-d35f-4de4-a1ff-81d1c30bdb04.png)

**Comment by wong2** [comment]
@ba32107 Seems your system is light mode but you're using Google in dark mode?

**Comment by ba32107** [comment]
Ah yes, you are correct. I am using a custom dark theme on Ubuntu and the system theme doesn't recognise that it's dark.
