### ISSUE TITLE
Will it be uploaded to Edge Addons?

### ISSUE THREAD

**Issue by Segilmez06** [wong2/chat-gpt-google-extension#5]
It will be great if we can also get it from Edge Addons.

**Comment by wong2** [comment]
Sure, I'll do it.

**Comment by wong2** [comment]
May I ask what's the difference of publishing the extension to Chrome Webstore and Edge Addons? As far as I know Edge can install extensions from Chrome Webstore too

**Comment by Segilmez06** [comment]
Edge users can install from Chrome Web Store but Edge Addons also automatically installs extensions to all sessions logged in with the same MS account. So, no need to install it again when the browser cache is deleted or a user installed Edge on another PC. That's why I suggested it.

**Comment by wong2** [comment]
Thanks for the explaination!

**Comment by Peri-albert** [comment]
maybe he couldn't visit Google

**Comment by Segilmez06** [comment]
> maybe he couldn't visit Google

Publishing to Chrome Web Store and Google Play Store requires a $5 developer account but publishing to Edge Addons is free. But on Edge Addons, it takes a bit of time for confirmation. Maybe he is waiting for confirmation.

**Comment by wong2** [comment]
I've published to Edge Addons, waiting for review

**Comment by bigplayer-ai** [comment]
> Edge users can install from Chrome Web Store but Edge Addons also automatically installs extensions to all sessions logged in with the same MS account. So, no need to install it again when the browser cache is deleted or a user installed Edge on another PC. That's why I suggested it.

Now I understand why my extension keeps disappearing.
