### ISSUE TITLE
Latest version doesn't work on Edge

### ISSUE THREAD

**Issue by xionghao132** [wong2/chat-gpt-google-extension#55]
the version of my Edge is the latest, while the extension does not work

**Comment by wong2** [comment]
what do you mean by doesn't work?

**Comment by xionghao132** [comment]
the chat box does not appear

**Comment by xionghao132** [comment]
load the extracted extension

**Comment by xionghao132** [comment]
but the google chrome works

**Comment by wong2** [comment]
It works for me. Can you have another try?

**Comment by xionghao132** [comment]
I hava found the problem,because i used the microsoft bing search box,thank you very much!!!
