### ISSUE TITLE
Feature request: try again button

### ISSUE THREAD

**Issue by joekendal** [wong2/chat-gpt-google-extension#61]
The try again option

**Comment by maniemks** [comment]
Why

**Comment by jacobhumston-school** [comment]
https://github.com/wong2/chat-gpt-google-extension/pull/39#issuecomment-1339577593

**Comment by wong2** [comment]
As I stated in the comment, I think this feature is not that necessary. I'll leave this issue for more comments.

**Comment by ShantanuJhaveri** [comment]
I think refreshing is right. There is no need for an additional button to do that.

**Comment by joekendal** [comment]
Fine, but we do need to address caching the response, shouldn't refetch every time navigating back after clicking on a result
