### ISSUE TITLE
Add timeout for chatgpt responding

### ISSUE THREAD

**Issue by wong2** [wong2/chat-gpt-google-extension#62]
If chatgpt takes too long(>30s?) to response, cancel the request and show and error message.

**Comment by wong2** [comment]
Sure, go ahead

**Comment by alihakimtaskiran** [comment]
30s is set to time out. Is this delay affected from depth of the question, namely so-called "thinking-time" of the algorithm. For clarity, is there any big difference in terms of computation time between asking an extremely hard question and easy question, such as. "Create a research paper about quantum mechanics" vs. "2+2=?".
