### ISSUE TITLE
no results displayed

### ISSUE THREAD

**Issue by u10k** [wong2/chat-gpt-google-extension#66]
![image](https://user-images.githubusercontent.com/22042799/206416490-220e7a00-0c0c-4511-81ba-7f5f23f3467a.png)

**Comment by wong2** [comment]
Sometimes the response is very slow, please retry

**Comment by 0num4** [comment]
@u10k 
Maybe your authentication is not working properly. When I created another chrome profile on the same PC and used another account, it was displayed instantly
