### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by fj3224013877** [wong2/chat-gpt-google-extension#69]
你好，我安装了它，但是我不知道该如何使用。我拥有openai账号，求大佬指点，非常感谢！

**Comment by Downvote-Hunter** [comment]
@fj3224013877 You install the extension [here](https://chrome.google.com/webstore/detail/chatgpt-for-google/jgjaeacdkonaoafenlfkkkmbaopkbilf), and then you use Google normally.
