### ISSUE TITLE
Feature request: support for iOS

### ISSUE THREAD

**Issue by hanbyul-kim** [wong2/chat-gpt-google-extension#70]
I tried to convert your extension using XCode to Safari on Mac and iPad.
The one on Mac works fine, as I expected.
The extension runs well on iPad Safari too, but it doesn't detect login session from the other tab.
![IMG_0801](https://user-images.githubusercontent.com/4781513/206512173-1e58b8e1-4eb9-44e5-8ed4-177fab6731dd.PNG)

Do you have any idea on this?

**Comment by jt-wang** [comment]
@hanbyul-kim The screenshot indicates that you may be in private mode, where sessions are not shared.
https://apple.stackexchange.com/questions/162864/keep-sessions-between-private-tabs

**Comment by hanbyul-kim** [comment]
> @hanbyul-kim The screenshot indicates that you may be in private mode, where sessions are not shared.
> https://apple.stackexchange.com/questions/162864/keep-sessions-between-private-tabs

Thanks for reply! However, I also tried in non-private mode. The result was same.

**Comment by wong2** [comment]
I'm not familiar with Safari extensions, can you show some code?

**Comment by hanbyul-kim** [comment]
There's nothing I wrote for the Safari web extension!
I just followed the instructions of [this article](https://www.vshsolutions.com/blogs/convert-chrome-extension-to-safari-web-extension/).
Take a look at it!

**Comment by wong2** [comment]
Merge with #110
