### ISSUE TITLE
Option to disable the extension by clicking on it again

### ISSUE THREAD

**Issue by spectkiller** [wong2/chat-gpt-google-extension#72]
Look, the extension is helpful, but most of the time, you don't need it. For example, all google searches aren't mainly a question to be answered, like searching about some mobile phone, searching for some shopping item, and other non-question inquiries.

I think it can afford to be disabled at that time. If I or anyone need the ChatGPT response, we just need to click it to enable it again.

**Comment by wong2** [comment]
Let's discuss here: https://github.com/wong2/chat-gpt-google-extension/issues/77
