### ISSUE TITLE
unfavorable black background for chatGPT output

### ISSUE THREAD

**Issue by sky31even** [wong2/chat-gpt-google-extension#74]
![image](https://user-images.githubusercontent.com/49628447/206608051-398b137e-6417-479c-88d9-411626de500b.png)

the output of the chatGPT is in black box as the image above.

i guess this might because of the plugin read the theme settings or something.

my default theme for windows(win11) is dark and so does the Chrome.

but the google search is in white theme.

please allow any customize settings on the dark/light theme choice of the chatGPT output.

**Comment by wong2** [comment]
Yeah, it's reading color theme of your system. So you're using Google in light mode while your system is in dark mode?

**Comment by yeliex** [comment]
the same to me.
use `background: transparent` is better

**Comment by IvanVnucec** [comment]
Removing the `background-color` css tag in the `.markdown-body` element might fix the not so appealing look:
![image](https://user-images.githubusercontent.com/50591550/206645933-da7272f5-a9d7-48cf-98c0-7cbe1240ba26.png)

**Comment by Sumat2222** [comment]
Even after downloading 1.2.1 and manually installing it in Chrome, still shows me 1.2.0 in the chrome://extensions and the black screen is still there. Anything that I am doing wrong?

**Comment by wong2** [comment]
No you're doing it right, i forgot to bump the version code. May i have a screenshot of your Google page?

**Comment by wong2** [comment]
Fixed in latest version

**Comment by sky31even** [comment]
> Yeah, it's reading color theme of your system. So you're using Google in light mode while your system is in dark mode?

yes...

**Comment by wong2** [comment]
You can now manually switch color in the extension settings!
