### ISSUE TITLE
https://chat.openai.com/auth/login?callbackUrl=https%3A%2F%2Fchat.openai.com%2F&error=OAuthSignin

### ISSUE THREAD

**Issue by joytianya** [wong2/chat-gpt-google-extension#80]
https://chat.openai.com/auth/login?callbackUrl=https%3A%2F%2Fchat.openai.com%2F&error=OAuthSignin

I can't log in, it keeps redirecting me to the login page. Is there a solution?

**Comment by davisphper** [comment]
I changed my browser to Safari and then tried again several times to log in successfully 🎉
