### ISSUE TITLE
It is hard to copy text while "loading" is in place

### ISSUE THREAD

**Issue by IvanVnucec** [wong2/chat-gpt-google-extension#82]
When I google something, the GPT text is showing on the screen word by word. When I try to select certain sentence in the loading GPT text to copy it, the selected text is flickering.

**Comment by JordanShackelford** [comment]
One possible solution is to use the user-select CSS property to control whether or not users can select text in the container element. By default, this property is set to auto, which means that the user can select text if the element is focusable (such as an input field or a link), but not if the element is not focusable (such as a div or a span).

To fix the flickering issue, you can set the user-select property to text on the container element, which will allow users to select and copy text from the container even if it is not focusable. For example:

`const container = document.createElement('div')
container.className = 'chat-gpt-container'
container.innerHTML = '<p class="gpt-loading">Waiting for ChatGPT response...</p>'

// Allow users to select text in the container
container.style.userSelect = 'text'
`
With this change, users should be able to select and copy text from the container element without it flickering and deselecting. Keep in mind that this may not be the only cause of the flickering issue, and there may be other factors at play that you will need to investigate and address.

**Comment by wong2** [comment]
Resolved
