### ISSUE TITLE
Show icon in Firefox toolbar

### ISSUE THREAD

**Issue by IvanVnucec** [wong2/chat-gpt-google-extension#84]
I like to have a view of the installed add-on's while browsing so I'm suggesting that we should implement add-on icon. 

Also, maybe when you click on the icon, the settings should appear or maybe another text prompt to get GPT responses.

**Comment by wong2** [comment]
Are you using firefox?

**Comment by IvanVnucec** [comment]
> Are you using firefox?

Yes, I'm using Firefox.

**Comment by wong2** [comment]
There is nothing to do when clicking the icon currently, so there is no need to show the icon in toolbar. I'll add one when the setting page is implemented.
