### ISSUE TITLE
其他搜索引擎界面引用chatgpt吗

### ISSUE THREAD

**Issue by bfqbpq567** [wong2/chat-gpt-google-extension#88]
1，目前只能在谷歌搜索引擎界面才有，在其他主流搜索引擎必应，百度，searx，f搜等没有。
2，在github上有人做了在其他搜索引擎上引用chatgpt，地址（https://github.com/josStorer/chat-gpt-search-engine-extension）但需要另外安装包。而作者大大你的在商店上就有扩展安装，这方便很多。希望可以增加。

**Comment by josStorer** [comment]
#31
