### ISSUE TITLE
Fix baidu support

### ISSUE THREAD

**Issue by wong2** [wong2/chat-gpt-google-extension#89]
@josStorer since baidu loads search result page without a page load, the extension will not be triggered.

**Comment by josStorer** [comment]
yes, currently have to make a refresh after a search

**Comment by josStorer** [comment]
i think we can add `action` to the search engine config file
like
`
baidu: {
    inputQuery: [],
    sidebarContainerQuery: [],
    appendContainerQuery: []
    action: {
        onMount: someFunction, // add some listener
        .....
    }
},
`

**Comment by josStorer** [comment]
> i think we can add `action` to the search engine config file like

should i create another issue for that?

**Comment by wong2** [comment]
No, we can discuss in this issue

**Comment by josStorer** [comment]
may i create a pull request to fix this with the above lifecycle actions, and then ask you to do a code review?

**Comment by wong2** [comment]
I don't we need general apis for `beforeMount`, `onMount` etc, what we need is run `run` after location changed for any reasons

**Comment by wong2** [comment]
Makes sense. i think we can put baidu support on hold temporarily

**Comment by josStorer** [comment]
I'll try to add the support in a generic way in my fork, maybe I can create a PR then and ask you to make a review, but of course, I won't have time today

**Comment by josStorer** [comment]
fixed in #93
