### ISSUE TITLE
Remember Session

### ISSUE THREAD

**Issue by Polydynamical** [wong2/chat-gpt-google-extension#9]
When the text output is too large for ChatGPT, it truncates the text. However, on the ChatGPT website you are able to say something like "please continue" and it will continue from where it left off. However, in the search, it does not seem to work as expected...

**Comment by wong2** [comment]
I think it doesn't make sense to input something like "continue" in Google search bar 😢  I'd prefer the suggestion by https://github.com/wong2/chat-gpt-google-extension/issues/10

**Comment by wong2** [comment]
Close as duplication of #10
