### ISSUE TITLE
Can't load the unpacked extension in Chrome

### ISSUE THREAD

**Issue by odragora** [wong2/chat-gpt-google-extension#94]
Hello and thank you for this great extension.

I'm trying to modify it and test it in my Chrome from Extension page.
I'm clicking Load Unpacked button, select the /src directory, and Chrome responds with an error:
`"Could not load javascript 'content-script.js'"`.

I can see that there is a `"content-script"` folder inside `/src`, but there is indeed no `"content-script.js"` file there.
Am I missing something?

**Comment by wong2** [comment]
Hi, you need to run `npm run build`, please follow the instructions in README
